# Configuración global de Prometheus para el sistema IPC
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

# Reglas de alertas (opcional)
rule_files:
  # - "alerts.yml"

# Configuración de recolección de métricas
scrape_configs:
  # Configuración para el servidor IPC
  - job_name: 'ipc-server'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['ipc-server:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: service
        replacement: 'ipc-server'

  # Métricas del propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      - target_label: service
        replacement: 'prometheus'

  # Métricas de Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    relabel_configs:
      - target_label: service
        replacement: 'grafana'

# Configuración de alerting
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'  # Comentado hasta implementar AlertManager
